### ISSUE TITLE
Getting ResourceNotFound Error

### ISSUE THREAD

**Issue by amalkabraham001** [danielsollondon/azvmimagebuilder#102]
Hi,

I was working on Azure Image builder using Azure DevOps Pipeline without any issues and was able to create VMs till yesterday. Today it started giving error like "resource not found"

<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. 

I checked with my colleague and he is also facing the same issue.  I tried selecting multiple images but all are giving same error.

**Comment by danielsollondon** [comment]
Sorry to hear this, where are you seeing this? Can you raise a case and we'll take a look, please ensure you select the right routing path and we will review in the daily triage: https://github.com/danielsollondon/azvmimagebuilder/issues/65
