### ISSUE TITLE
 excludeFromLatest not working

### ISSUE THREAD

**Issue by tsrob50** [danielsollondon/azvmimagebuilder#106]
I tested the  "excludeFromLatest" : true setting and the image version was not excluded from the latest version after the image build.

**Comment by danielsollondon** [comment]
hi @tsrob50 - Can you raise a case here and I will triage this with the CSS team please?
https://github.com/danielsollondon/azvmimagebuilder/blob/master/troubleshootingaib.md#troubleshooting-azure-vm-image-build-aib-failures

We will need to know:
* AIB Service region
* Publisher / Offer / SKU in the customization.log
* template name and subID

Thanks,
