### ISSUE TITLE
Pass KeyVault secret to inline script as Argument

### ISSUE THREAD

**Issue by brandonjclark78** [danielsollondon/azvmimagebuilder#112]
Love the work you are doing in this task.  However, one major thing holding me back from adopting is that it doesn't seem possible to pass a KeyVault secret to the inline script as an argument.

Example, instead of just:  & 'c:\buildArtifacts\webapp\webconfig.ps1'

I'd like to be able to pass that KeyVault secret like:  & 'c:\buildArtifacts\webapp\webconfig.ps1' $KeyVaultSecret

**Comment by danielsollondon** [comment]
Thank you for the kind words @brandonjclark78!

Apologies for the delay here, if you see this issue still, please raise here: https://github.com/azure/azvmimagebuilder
