### ISSUE TITLE
Use faster storage for Image builder VM

### ISSUE THREAD

**Issue by rfolkers** [danielsollondon/azvmimagebuilder#114]
Currently the VM that's being created for running the provisioners is using a standard HDD managed disk. The Standard HDD SKU is not known for it's outstanding performance, so it would be nice to have the option to use different SKU's, for example premium storage.
I believe this would be an appropriate place to determine the storage sku:

"vmProfile": 
                    {
                    "vmSize": "Standard_D2_v2",
                    "osDiskSizeGB": 127
                    },

**Comment by danielsollondon** [comment]
Apologies for the delay here, if you see this issue still, please raise here: https://github.com/azure/azvmimagebuilder
