### ISSUE TITLE
Path change for W10 optimisation script

### ISSUE THREAD

**Issue by ii-batman** [danielsollondon/azvmimagebuilder#117]
_$osOptURL = 'https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/archive/master.zip'_ is no longer valid.
The PowerShell script is at: _https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/main/Win10_VirtualDesktop_Optimize.ps1_

**Comment by rbnmk** [comment]
$osOptURL = https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/archive/master.zip'

needs to be changed to:

$osOptURL = 'https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/archive/main.zip'

I think they renamed their branch to 'main'

**Comment by ii-batman** [comment]
@rbnmk @danielsollondon 
I am having huge difficulty in creating the template via json files, I am using every direction from Dan's repo.

So I forked it and change the locations accordingly but the template build still hangs:

>   azure-arm: VERBOSE: Created 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\2009\LGPO\DomainSysvol\GPO\Machine\registry.pol'.
  azure-arm: VERBOSE: Adding 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\2009\LGPO\DomainSysvol\GPO\User\'.
  azure-arm: VERBOSE: Created 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\2009\LGPO\DomainSysvol\GPO\User\registry.pol'.
  azure-arm: VERBOSE: Created 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\2009\LICENSE'.
  azure-arm: VERBOSE: Created 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\Build_JSON_Files.ps1'.
  azure-arm: VERBOSE: Created 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\EULA.txt'.
  azure-arm: VERBOSE: Adding 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\LGPO\'.
  azure-arm: VERBOSE: Created 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\LGPO\LGPO.exe'.
  azure-arm: VERBOSE: Created 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\README.md'.
  azure-arm: VERBOSE: Created 'C:\optimize\Virtual-Desktop-Optimization-Tool-main\Win10_VirtualDesktop_Optimize.ps1'.
  azure-arm: VERBOSE: Performing the operation "Set-ExecutionPolicy" on target "RemoteSigned".
  azure-arm: Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
  azure-arm: a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
  azure-arm: execution policy of Bypass. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
  azure-arm: information please see "Get-Help Set-ExecutionPolicy".
  azure-arm: At C:\Windows\Temp\script-60c77125-0a10-cb73-9081-5a345e90e0ed.ps1:15 char:2
  azure-arm: +  Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force -Verbose
  azure-arm: +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  azure-arm:     + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
  azure-arm:     + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
  azure-arm: Patch: Disabling Set-NetAdapterAdvancedProperty
  azure-arm:     This Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment.
  azure-arm:     THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
  azure-arm:     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.  We grant
  azure-arm:     You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form
  azure-arm:     of the Sample Code, provided that You agree: (i) to not use Our name, logo, or trademarks to market Your software product in
  azure-arm:     which the Sample Code is embedded; (ii) to include a valid copyright notice on Your software product in which the Sample Code
  azure-arm:     is embedded; and (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits,
  azure-arm:     including attorneys' fees, that arise or result from the use or distribution of the Sample Code.
  azure-arm:
  azure-arm:     Microsoft provides programming examples for illustration only, without warranty either expressed or
  azure-arm:     implied, including, but not limited to, the implied warranties of merchantability and/or fitness
  azure-arm:     for a particular purpose.
  azure-arm:
  azure-arm:     This sample assumes that you are familiar with the programming language being demonstrated and the
  azure-arm:     tools used to create and debug procedures. Microsoft support professionals can help explain the
  azure-arm:     functionality of a particular procedure, but they will not modify these examples to provide added
  azure-arm:     functionality or construct procedures to meet your specific needs. if you have limited programming
  azure-arm:     experience, you may want to contact a Microsoft Certified Partner or the Microsoft fee-based consulting
  azure-arm:     line at (800) 936-5200.
  azure-arm:
  azure-arm:     For more information about Microsoft Certified Partners, please visit the following Microsoft Web site:
  azure-arm:     https://partner.microsoft.com/global/30000104

Please help - I can install every app I need but never been able to run the W10 optim script from automation.
Thanks Everyone

**Comment by rbnmk** [comment]
Yes, I found that out too. The windows optim script needs an -acceptEula
switch, but I don't think it's there in the examples. I took the example
scripts and updated them with proper configuration in order for me to get
through the example steps. (They are in my PowerShell repo, but I might
remove them after trying out AIB)

Op ma 14 jun. 2021 18:30 schreef ii-batman ***@***.***>:

**Comment by ii-batman** [comment]
@rbnmk 
For your visibility also. @rbnmk

**Comment by danielsollondon** [comment]
thank you @rbnmk
