### ISSUE TITLE
Azure Image Builder Template Submission Failure

### ISSUE THREAD

**Issue by naveenkt59** [danielsollondon/azvmimagebuilder#119]
Hi,
I am trying to build a Custom Image using Azure Image Builder Service for a Customer. The Image Template Submitting fails with Error “Internal error occurred. This is a generic error. To identify possible causes, go to https://aka.ms/azvmimagebuilderts.” I have also checked the Reference URL "https://aka.ms/azvmimagebuilderts"  to identify possible causes for this Error to Occur and tried all the Suggestions for the above Error...but it didnt work.
Details about the Image Template JSON:
•	Uses a User Assigned Managed Identity
•	Install app using sudo apt-get command
•	Deploy the Image in a Shared Image Gallery with replication to EAST US and WEST US Region.
•	The User Assigned Managed Identity is assigned Contributor Role for the Resource Group containing SIG.

Any Suggestions to resolve this error will be very helpful.

**Comment by kof-f** [comment]
Hey @naveenkt59 if you're still experiencing this issue, please raise it in the official Image Builder repo: https://github.com/Azure/azvmimagebuilder
