### ISSUE TITLE
When trying to build the image error The term 'Start-AzImageBuilderTemplate' is not recognized

### ISSUE THREAD

**Issue by saleemahmad2** [danielsollondon/azvmimagebuilder#120]
After issuing this command Start-AzImageBuilderTemplate -ResourceGroupName $imageResourceGroup -Name $imageTemplateName -NoWait
I get the error as below:
Start-AzImageBuilderTemplate: The term 'Start-AzImageBuilderTemplate' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I am using PowerShell Version 7.1.5 on Windows 10. What do I need to get this Start-AzImageBuilderTemplate command and what version do we need? This is the last step in building the image, any help would be most appreciated.
Saleem

**Comment by HenryGelderbloem** [comment]
You need install the AzImageBuilderTemplate PowerShell module 

`Install-Module -Name Az.ImageBuilder`

**Comment by danielsollondon** [comment]
thank you @HenryGelderbloem!

If you need any more assist, please raise in the new repo.
