### ISSUE TITLE
Multiple copies within same region?

### ISSUE THREAD

**Issue by durrante** [danielsollondon/azvmimagebuilder#121]
Not an issue as such, is it possible to add multiple copies of an image within the Azure Compute Gallery using a template?

I can see that it's possible to add multiple regions, but I'm looking to add multiple copies within the same region via the template .json, if possible?

**Comment by danielsollondon** [comment]
Apologies for the delay here, if you see this issue still, please raise here: https://github.com/azure/azvmimagebuilder
