### ISSUE TITLE
DevOps Task - Not flagging destination image as LATEST to Azure Compute Gallery

### ISSUE THREAD

**Issue by rrberger** [danielsollondon/azvmimagebuilder#125]
Hi all,

I am struggling to get this issue resolved. I've put an issue in to Azure support, and done a ton of reading through the documentation, Git issues, and I am at a wall with this issue.

I am using the AIB DevOps task to pull a source image from our Azure Compute Gallery (lets say, version 1.0.0), run some customizers (installs the new build of the software my company develops) and then pushes that new image back to our Azure Compute Gallery (as say, version 1.0.1). My expectation would be after the AIB task runs successfully, our LATEST version of our Image Definition would be updated with 1.0.1, from 1.0.0. But this is not happening. Our Scale Set that is hooked into the Azure Compute Gallery to run Azure DevOps Pipelines continues to pull the previous version until I **manually** swap it around in the Scale Set -> Operating System dialog box from the Azure Portal. Even if I run Az CLI commands against the scale set, it shows the old version of the image UNTIL I manually change the version around in the dialog box below.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/60238330/163863562-5927cf4d-bb0f-413d-9412-f18e7b23818b.png">

The AIB task is not flagging the **destination image** as latest, and to me this feels like that should not be the case.

Can anyone point me in the right direction with this? I am stuck and this is a blocker for the solution I've been working on that incorporates the AIB, Azure Compute Gallery, and some Azure DevOps pipelines.

![image](https://user-images.githubusercontent.com/60238330/163863798-db9b9a5a-0b67-4a22-bb3d-44857159f010.png)

**Comment by kof-f** [comment]
Hey @ryanberger-az I'm raising this issue with our team and will get back to you.

**Comment by danielsollondon** [comment]
Apologies for the delay here, if you see this issue, please raise here: https://github.com/azure/azvmimagebuilder
