### ISSUE TITLE
Specify for who permission is granted

### ISSUE THREAD

**Issue by imaculate** [danielsollondon/azvmimagebuilder#13]
This section mentions granting access but not the recipient. An objectId is provided in the command but it is not clear who it belongs to, the user? managed Identity? 

https://github.com/danielsollondon/azvmimagebuilder/tree/master/quickquickstarts/7_Creating_Custom_Image_using_MSI_to_Access_Storage#step-2-assign-permissions-for-the-resource-group-where-the-image-will-be-created

**Comment by danielsollondon** [comment]
Hi, apologies for the delay in getting back to you. When image builder runs, its Service Principal needs permissions to distribute the image into either a Managed Image or Shared Image Gallery, so you need to give contributor rights to the Image Builder Service Principal, that is what the objectID is. Apologies, this is not clear, I am working on a docs update, I will address this.

Does this explanation help?

**Comment by imaculate** [comment]
This helps, thanks!

**Comment by danielsollondon** [comment]
Hi @imaculate - As promised, we have documented the permissions:
https://github.com/danielsollondon/azvmimagebuilder/blob/master/aibPermissions.md#azure-vm-image-builder-permissions-explained-and-requirements

Thanks!
