### ISSUE TITLE
0_installConfFsLogix.ps1 - causes multisession AIB builds to fail

### ISSUE THREAD

**Issue by LadtoHelp** [danielsollondon/azvmimagebuilder#130]
There seems to be an issue with this script whereby multisession images fail to complete the imaging process. 
I have worked around by editing this template https://raw.githubusercontent.com/azure/azvmimagebuilder/master/solutions/14_Building_Images_WVD/armTemplateWVD.json by adding 
                        "validExitCodes": [0,267014],
to the installFsLogix json block

**Comment by michael-novak-80** [comment]
I can confirm this, we've run into the same problem when deploying latest AVD image template. 
Actual packer step that is failing is:
[INFO] command 'powershell -executionpolicy bypass -file "C:/Windows/Temp/packer-elevated-shell-6363c307-fc28-5c5a-e58f-ce705e0ef871.ps1"' exited with code: 267014

**Comment by danielsollondon** [comment]
Apologies for the delay here, please raise further issues here: https://github.com/azure/azvmimagebuilder
