### ISSUE TITLE
Triggering a Build from Template then Responing to Updates Async

### ISSUE THREAD

**Issue by blueboxes** [danielsollondon/azvmimagebuilder#134]
I am trying to build an image from a template using CI/CD but have two issues. 

1) The az command 

```
az resource invoke-action \
--subscription $(subscriptionId) \
--resource-group $(resourceGroup) \
--resource-type Microsoft.VirtualMachineImages/imageTemplates \
--name $(templateName) \
--action Run;
```

This has no --no-wait feature yet. So I would like to use the REST API to start it off but I cannot see the image builder in the REST API documentation.

2) Once it has started the build I can see no way to subscribe to updates so I know when it has succeeded or failed.

I feel like I am missing something, any pointers would be useful.

**Comment by danielsollondon** [comment]
Apologies for the delay here, Please raise further issues here: https://github.com/azure/azvmimagebuilder
