### ISSUE TITLE
WindowsServer:2016-Datacenter Builds Failing

### ISSUE THREAD

**Issue by danielsollondon** [danielsollondon/azvmimagebuilder#14]
We are seeing build failures issue with the latest MicrosoftWindowsServer:WindowsServer:2016-Datacenter source image, version: 14393.3326.1911120150

If you look in the customization.log, you will see this error:
[9bd218e8-11c5-4820-87a8-c5f667c41c7d] PACKER OUT Build 'azure-arm' errored: Timeout waiting for WinRM.
[9bd218e8-11c5-4820-87a8-c5f667c41c7d] PACKER ERR 2019/11/26 06:54:32 machine readable: azure-arm,error []string{"Timeout waiting for WinRM."}

This has just started happening with this image version, if we rollback to the previous version, there is no issue.
 
MicrosoftWindowsServer:WindowsServer:2016-Datacenter: 14393.3274.1910061629
 
We are investigating this with the Windows team, updates will be posted here.

**Comment by danielsollondon** [comment]
Hi - just an update, testing shows using the more recent image version, 14393.3326.1911120150, 14393.3384.1912042333, then the build fails. But if you change the default vm_size that image builder uses, to "Standard_D2_v2", then the builds succeed, we are working with the windows team to isolate the cause.

**Comment by danielsollondon** [comment]
Further update, we have been doing further investigation with the Windows PG, we have found an issue when using Standard_D1_v2 and the Nov/Dev WinSvr 2016 images, which is mitigated by increasing the vm size to Standard_D2_v2, I am waiting for details on the solution.

As an FYI, if you are using the Azure DevOps task, you see a generic 200 error, but if you check the customization.log, in the staging resource group, you will see the WinRM error.

**Comment by AlexeyKarpushin** [comment]
Hi Daniel,
I'm not sure if our issue is the same as this one, but it looks similar. Hope this will be useful.
We're using Packer (not Image Builder) to create Win-2016 based images in Azure according to [this doc](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/build-image-with-packer), and most, but not all of our builds fail with WinRM timeout. I found that it related to some error in WinRM certificate provisioned to temp VM by Packer. If I run `Test-WSMan -ComputerName temp_vm_IP -usessl` against the broken temp machine it shows the following error:

```
The server certificate on the
destination computer (30.0.0.133:5986) has the following errors:
Encountered an internal error in the SSL library.
```

If I run the same command against the temp machine which was able to connect, there is no error like this. Also I found that I can make the temp machine works by generating a self-signed cert on it and reconfiguring WinRM listener with a new cert. Here are the steps:

• Set a huge WinRM timeout in Packer config to have enough time for the next steps
• Grab the temp machine name from the Packer log, keep the build running
• Find the temp machine on the Azure portal and execute the following via Run Command
```
$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "$env:COMPUTERNAME"
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force
Stop-Service winrm
Start-Service winrm
```
• After this Packer will be able to connect to the temp machine

Our config:
Machine where Packer is running: Azure VM with Windows Server 2016 Datacenter
Packer config:
```
      "os_type": "Windows",
      "image_publisher": "MicrosoftWindowsServer",
      "image_offer": "WindowsServer",
      "image_sku": "2016-Datacenter",
      "vm_size": "Standard_D16s_v3"
```

Kind regards,
Alexey

**Comment by danielsollondon** [comment]
@AlexeyKarpushin - thank you so much for taking the time to write this up, I will try this, and come back to you. I have also had other reports of other packer users having issues, so this may help them.

**Comment by ciaranj** [comment]
This also happens with the '2019-Datacenter' SKU too. (Workaround from @AlexeyKarpushin  also works)

**Comment by akingscote** [comment]
@AlexeyKarpushin thanks! Ive tried your workaround and it did the job!
for complete clarity, here is the command i used from my PC with AZ Cli configured.
```
az vm run-command invoke  --command-id RunPowerShellScript --name <vm name> -g <resource group> --scripts @testScript.ps1
```

Where <vm name> is the packer virtual machine name, <resource group> is the packer resource group name and testScript.ps1 is contains those lines you posted.

The interesting bit of my packer config is 
```
"os_type": "Windows",
"image_publisher": "MicrosoftWindowsServer",
"image_offer": "WindowsServer",
"image_sku": "2019-Datacenter",
"communicator": "winrm",
"winrm_use_ssl": true,
"winrm_insecure": true,
"winrm_timeout": "10m",
```

Thanks again

**Comment by danielsollondon** [comment]
Quick update from the Windows team, they have identified an issue with the Windows Server 2016 image (November onwards), that impacts the time to initiate a WinRM connection, we are still working on this, and will update again mid next week. In the meantime please try increasing the Packer timeout to 30mins, and try a larger VM size.

**Comment by ciaranj** [comment]
FWIW, if you run the above workaround and create a new ‘fixed’ base image then use that as your base image instead of the Microsoft provided one your winrm issues go away so you only have to take the manual intervention hit once. (Until Microsoft fix their base image!)

**Comment by adamrushuk** [comment]
Thanks for the update @danielsollondon . 
Are the Windows team also looking at the Windows Server 2012 image, as many of us have also had intermittent issues using that too; even with 30+ min winrm timeout, and larger VMs?

**Comment by danielsollondon** [comment]
Hi @adamrushuk  - no, they are just focused on Windows Server 2016, are you seeing this with image builder, packer, or both? thanks

**Comment by danielsollondon** [comment]
**Update from the Windows team**: Windows Server 2016 images since November 2019 can have a post first boot performance issue related to an OS code integrity operation.  This issue is more pronounced on small Azure VM sizes (with lower throughput and IO) rendering the VM not immediately usable after first boot. The performance issue is mitigated in February 2020 images and forward. Please use the latest February Windows Server 2016 image once it is available from the Marketplace (ETA 2/17).

**Comment by danielsollondon** [comment]
Hi,
Windows Server 2016 Image version: 14393.3504.2002070914 has been released, after testing image builder, this builds successfully.

Please reopen if you see any further issues.

Thanks,

Dan

**Comment by Marcus-James-Adams** [comment]
Please reopen, if anything this issue is getting worse
