### ISSUE TITLE
Principal cf32a0cc373c47c991560db11f6a6dfc

### ISSUE THREAD

**Issue by VaperWare** [danielsollondon/azvmimagebuilder#17]
when I run the following,  it come back with the return error , I have verified all resource providers are registered and the AZ module is the latest, please assist

Returned error
New-AzRoleAssignment : Principal cf32a0cc373c47c991560db11f6a6dfc does not exist in the directory f32b97f0-efb8-4bc3-91ee-18a6e5f635c9.

Command executed
PS C:\GitHub\AIS\AFC> New-AzRoleAssignment `
>>    -ObjectId cf32a0cc-373c-47c9-9156-0db11f6a6dfc `
>>    -Scope /subscriptions/$subscriptionID/resourceGroups/$imageResourceGroup `
>>    -RoleDefinitionName Contributor

**Comment by danielsollondon** [comment]
Hi, this is the AppID of the Image Builder SPN, cf32a0cc-373c-47c9-9156-0db11f6a6dfc, you need the ObjectID: ef511139-6170-438e-a6e1-763dc31bdf74

Here is a PS example:
https://github.com/danielsollondon/azvmimagebuilder/tree/master/quickquickstarts/1_Creating_a_Custom_Win_Shared_Image_Gallery_Image#step-1-set-up-environment-and-variables

LMK if that helps?

**Comment by danielsollondon** [comment]
@VaperWare - did this help? Please let me know if you are still have issues.

**Comment by danielsollondon** [comment]
temporarily closing, please reopen if further questions.
