### ISSUE TITLE
I would like to use an existing SQL server image as the base image

### ISSUE THREAD

**Issue by shardulkul** [danielsollondon/azvmimagebuilder#21]
Hello,
I'm able to specify a different `source` (see below excerpt) as the base image. However, I would like to customize the base image to enable certain features. For example, I want to allow SQL authentication and create an SA account. How can I accomplish this?

```
       "source": {
            "type": "PlatformImage",
            "publisher": "MicrosoftSQLServer",
            "offer": "sql2019-ws2019",
            "sku": "sqldev",
            "version": "15.0.200114"
        },
```

**Comment by danielsollondon** [comment]
Hi @shardulkul - sorry for the delay, I have not worked with SQL for a long time now, the SQL communities would be a better place for remote configuration with script, but I did see there are PS cmdlets for configuring SQL: https://docs.microsoft.com/en-us/powershell/module/sqlserver/?view=sqlserver-ps

Not sure if that is useful?

**Comment by danielsollondon** [comment]
closing, please reopen if this is still an issue.
