### ISSUE TITLE
resource type 'imageTemplates

### ISSUE THREAD

**Issue by drewkg** [danielsollondon/azvmimagebuilder#22]
When revisiting this after some time, to see if progress had been made, we are receiving the issue below :-

[error]Error: put template call failed for template t_1583248310130 with error: The subscription is not registered for the resource type 'imageTemplates'. Please check that the resource type exists and re-register for this provider in order to have access to this resource type. (CODE: 409)

**Comment by danielsollondon** [comment]
Hi @drewkg - it looks like you are using the DevOps task. Can you check that the subscription that the DevOps task is running in has the feature still registered?

PS
https://github.com/danielsollondon/azvmimagebuilder/tree/master/quickquickstarts/0_Creating_a_Custom_Windows_Managed_Image#register-for-image-builder--vm--storage-features

AZ CLI
https://github.com/danielsollondon/azvmimagebuilder/tree/master/quickquickstarts/0_Creating_a_Custom_Linux_Managed_Image#register-for-image-builder--vm--storage-features

LMK, if this is showing registered?

**Comment by danielsollondon** [comment]
closing, please reopen if still an issue.
