### ISSUE TITLE
Service principle not in subscription

### ISSUE THREAD

**Issue by BladeFireLight** [danielsollondon/azvmimagebuilder#23]
I get this error trying to setup our tenant.

New-AzRoleAssignment: Principal ef5111396170438ea6e1763dc31bdf74 does not exist in the directory

I get the feeling I'm missing some pre-req not in the docs

**Comment by danielsollondon** [comment]
Hi, can you confirm you have registered for the feature please?

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/image-builder-gallery#register-the-features

**Comment by danielsollondon** [comment]
Hi @BladeFireLight - In addition we have documented the permissions:
https://github.com/danielsollondon/azvmimagebuilder/blob/master/aibPermissions.md#azure-vm-image-builder-permissions-explained-and-requirements

Closing, please let us know if you still have an issue.
