### ISSUE TITLE
Run Elevated Commands Hang on some Win10 SKUs

### ISSUE THREAD

**Issue by danielsollondon** [danielsollondon/azvmimagebuilder#24]
We are finding that image builder builds are hanging when configuring rs5-enterprisen sku and rs5-pro sku, this is when the PowerShell customizer is running commands as an elevated user, in my repro, just creating directories. This does not happen with rs5-evd.
 
We are investigating what is happening here.

**Comment by danielsollondon** [comment]
A workaround whilst we work to resolve this, convert the inline commands into a script, and run that elevated, the command succeeds

**Comment by tjsullivan1** [comment]
Hi @danielsollondon - 

I seem to still have an issue even when running as a script. I have the script in an Azure Storage Blob, with my user assigned identity configured with the permissions as described in step 4 here: https://github.com/danielsollondon/azvmimagebuilder/tree/master/quickquickstarts/7_Creating_Custom_Image_using_MSI_to_Access_Storage

This script is rather lengthy, so not sure if that could have something to do with it, but I will do some more testing and let you know.

Tim

**Comment by danielsollondon** [comment]
Hi @tjsullivan1 - does the script hang, does it start to run?

**Comment by tjsullivan1** [comment]
I believe it starts to run, but when I run in elevated mode it doesn't seem as verbose as non-elevated shells. I've dropped you a message with some logs.

**Comment by GrahamHassall** [comment]
I see this with the 19h2-ent sku as well

everything before the elevated script runs as expected, but as soon as it tries to run the elevated script, all progress stops.
the last log entry shows the elevated script being started. I would suspect that the build VM is now patiently waiting for someone to acknowledge a UAC prompt

**Comment by mcphailt** [comment]
I too have have experienced the issue with the ent sku, the Evd sku is ok.  Currently working with Microsoft support.  In the log it appears to download and attempt the launch of script but hangs, none of the cmds process.

**Comment by danielsollondon** [comment]
Quick update, we are working on this still, we will come back to the thread. @mcphailt , can you email me your case number please? danis@microsoft.com

**Comment by danielsollondon** [comment]
Quick update, we are still working on this with the Win PG, no easy options, but will come back with an update within 3 weeks.

**Comment by danielsollondon** [comment]
Further update, we have identified possible options to resolve this, and are in the process of evaluating and testing. This step will take us another 4 weeks as we need to be careful that we do not introduce regressions.

**Comment by danielsollondon** [comment]
Quick update, the dev work is in progress, and you should be seeing the initial part of the solution ship within 2 weeks.

**Comment by shawntmeyer** [comment]
Hello Daniel,

Have you heard anything from the PG?

Shawn Meyer
Microsoft CE

**Comment by GrahamHassall** [comment]
Hello Daniel,
Is there any update for this issue?
I'm sure it won't surprise you that the issue is still present in 20H2-Ent as well

**Comment by GrahamHassall** [comment]
Hi @danielsollondon,

Can we have an update on this issue please.

**Comment by danielsollondon** [comment]
Hi @tjsullivan1 , @shawntmeyer , @GrahamHassall, and everyone, sorry I haven't come back, its been hectic and trying to catch up. We now have a new setting '"runAsSystem": true,' this will run the powershell customizer with localSystem and bypass the issue. More details here:

https://github.com/danielsollondon/azvmimagebuilder/tree/master/solutions/14_Building_Images_WVD#tips-for-building-windows-images-with-aib

**Comment by GrahamHassall** [comment]
Thanks @danielsollondon 
runAsSystem is working for me (tested on 19H2 Ent, 19H2 evd, 20H2 Ent & 20H2 evd)
I had to fix an application install in my customization script, which didn't like installing under the system account and I have a new issue with Windows Update customizer on the 20H2 images - I appreciate 20H2 is not supported yet but it might be useful feedback for you (build consistently gets stuck waiting for the reboot after windows updates are installed - can be "rescued" by manually rebooting the build host from the portal after it gets stuck)

**Comment by danielsollondon** [comment]
Hi @GrahamHassall - Can you raise a case for this, and we will triage it: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#getting-support

**Comment by LManning-Dev** [comment]
Looks like thins is still an issue with win10-22h2-ent? I have tried RunAsSystem as well, but runElevated just hangs the Azure Image Builder. Opening a ticket now. Thank you
