### ISSUE TITLE
SysPrep failing on 2019

### ISSUE THREAD

**Issue by drewkg** [danielsollondon/azvmimagebuilder#28]
This is a new issue, but the deprovisioning script appears to be a constant loop. 

[d50d81fb-d7cd-4094-9715-e11e39eda8ef] PACKER OUT ==> azure-arm: At C:\DeprovisioningScript.ps1:3 char:9
[d50d81fb-d7cd-4094-9715-e11e39eda8ef] PACKER OUT ==> azure-arm: + while ((Get-Service WindowsAzureTelemetryService).Status -ne 'Running ...
[d50d81fb-d7cd-4094-9715-e11e39eda8ef] PACKER OUT ==> azure-arm: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[d50d81fb-d7cd-4094-9715-e11e39eda8ef] PACKER OUT ==> azure-arm:     + CategoryInfo          : ObjectNotFound: (WindowsAzureTelemetryService:String) [Get-Service], ServiceCommandExcep
[d50d81fb-d7cd-4094-9715-e11e39eda8ef] PACKER OUT ==> azure-arm:    tion
[d50d81fb-d7cd-4094-9715-e11e39eda8ef] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
[d50d81fb-d7cd-4094-9715-e11e39eda8ef] PACKER OUT ==> azure-arm:
[d50d81fb-d7cd-4094-9715-e11e39eda8ef] PACKER OUT ==> azure-arm: Get-Service : Cannot find any service with service name 'WindowsAzureTelemetryService'.

**Comment by danielsollondon** [comment]
Hi @drewkg - sorry to hear this. Can you share details of your template, so I can reproduce this?Specifically the source, any customizations that are changing the sys prep command, or removing any existing features / or services? Thanks!

**Comment by drewkg** [comment]
@danielsollondon her is a stripped down version of our template, we are using the ARM method to upload (I have confirmed that without any customisations the issue still exists).  We are using a User Assigned Identity for access to a Storage Account (this was working well) I don't know if that is causing the issue.

{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "imagetemplatename": {
      "type": "string"
    },
    "svclocation": {
      "type": "string"
    },
    "publisher": {
      "type": "string"
    },
    "offer": {
      "type": "string"
    },
    "sku": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "customizestepname": {
      "type": "string"
    },
    "customizescriptpath": {
      "type": "string"
    },
    "galleryImageId": {
      "type": "string"
    },
    "sharedgalimagename": {
      "type": "string"
    },
    "destinationregion": {
      "type": "string"
    }
  },
  "variables": {
    "resourceid": "[concat(parameters('galleryImageId'), parameters('sharedgalimagename'))]"
  },
  "resources": [
    {
      "name": "[parameters('imagetemplatename')]",
      "type": "Microsoft.VirtualMachineImages/imageTemplates",
      "apiVersion": "2019-05-01-preview",
      "location": "[parameters('svclocation')]",
      "dependsOn": [],
      "identity": {
        "type": "UserAssigned",
        "userAssignedIdentities": {
          "<Add User Assigned Identity here>": { }
        }
      },
      "properties": {
        "source": {
          "type": "PlatformImage",
          "publisher": "[parameters('publisher')]",
          "offer": "[parameters('offer')]",
          "sku": "[parameters('sku')]",
          "version": "[parameters('version')]"
        },
        "buildTimeoutInMinutes": 90,
        "vmProfile": {
          "vmSize": "Standard_D4_v3"
        },
        "customize": [

        ],
        "distribute": [
          {
            "type": "SharedImage",
            "galleryImageId": "[variables('resourceid')]",
            "runOutputName": "[parameters('sharedgalimagename')]",
            "aritfactTags": {
              "source": "azVmImageBuilder",
              "releaseStatus": "staging",
              "type": "sigonly"
            },
            "replicationRegions": [
              "westcentralus",
              "eastus"
            ]
          }
        ]
      }
    }
  ]
}


{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "imagetemplatename": {
      "value": "TestBuilder"
    },
    "svclocation": {
      "value": "westcentralus"
    },
    "publisher": {
      "value": "MicrosoftWindowsServer"
    },
    "offer": {
      "value": "WindowsServer"
    },
    "sku": {
      "value": "2019-Datacenter"
    },
    "version": {
      "value": "latest"
    },
    "customizestepname": {
      "value": ""
    },
    "galleryImageId": {
      "value": "<Gallery ID here>"
    },
    "sharedgalimagename": {
      "value": "DriveTrainWinPS01"
    },
    "destinationregion": {
      "value": "westcentralus"
    }
  }
}

**Comment by danielsollondon** [comment]
Thanks I will test this tomorrow.

**Comment by danielsollondon** [comment]
Hi @drewkg - I checked a build with limited customizations, I could not reproduce a build failure, although you see the errors you pulled out, eventually the sys prep completes successfully. Can you send me your steps and the full customization.log to danis@microsoft.com

**Comment by danielsollondon** [comment]
Hi All, we can repro this issue, the dev team are working on this now, expect an update today.

Apologies for the inconvenience.

**Comment by danielsollondon** [comment]
Hi @drewkg - we have located an issue with **westcentralus** region and windows images, to workaround this now, please change to an alternative region. I will be documenting a workaround, if you need to use this region.

**Comment by drewkg** [comment]
Hi @danielsollondon Thanks for the information, there is no technical region we are running in that region, we will move to East US or West US and test again and confirm the solution.

**Comment by drewkg** [comment]
@danielsollondon I can confirm that moving the location to West US has resolved this issue for us.  Thanks for the prompt information and workaround.

**Comment by danielsollondon** [comment]
@drewkg - this has been resolved now, the westcentralus should not see this issue again. thanks for raising this!
