### ISSUE TITLE
BadSharedImageDistribute error when trying to create image

### ISSUE THREAD

**Issue by kfprugger** [danielsollondon/azvmimagebuilder#29]

**Comment by kfprugger** [comment]
![image](https://user-images.githubusercontent.com/20729981/79673766-a1f78c80-81aa-11ea-998e-a636113ff9a1.png)

**Comment by danielsollondon** [comment]
Hi @kfprugger - sorry you have encountered this, I will look into this today. Quick question, did you setup the permissions for the image builder SPN to write to the Shared Image Gallery?

https://github.com/danielsollondon/azvmimagebuilder/blob/master/aibPermissions.md#setting-aib-spn-permissions-to-use-source-custom-image-and-distribute-a-custom-image

Thanks,

**Comment by danielsollondon** [comment]
Hi @kfprugger - we checked the backend, this is permissions related, please check the permissions above and let me know if that resolves?

**Comment by TimMullender** [comment]
We're seeing this error when trying to use a Shared Image Gallery and a User Assigned MSI in the same template, one or the other is fine but both together give us the reported error.  The script we are using last run successfully at the start of March

The following is a simplified version of what we are doing based on the quick start examples

az resource show: [azImageTemplateCreationFailure.log](https://github.com/danielsollondon/azvmimagebuilder/files/4523528/azImageTemplateCreationFailure.log)

`Deployment failed. Correlation ID: a0f72b68-3989-49ae-9cb3-23b52f35f579. Not authorized to access the resource: /subscriptions/38***30/resourceGroups/DEV/providers/Microsoft.Compute/galleries/WD_FRP_Temp_Images/images/AzureZone-2.15. To resolve this issue, go to https://aka.ms/azvmimagebuilderts.`

Is there something different we need to do for permissions now, in this scenario?

**Comment by danielsollondon** [comment]
@TimMullender - Apologies for the inconvenience, please see #31

**Comment by danielsollondon** [comment]
@kfprugger - did the suggestion resolve you? If not, please re-open.
