### ISSUE TITLE
Azure VM Builder fails for Windows image build when using User Identity

### ISSUE THREAD

**Issue by sajithvasu** [danielsollondon/azvmimagebuilder#30]
Hello,
Thanks for the sample for using azure VM image builder. I tried few of them and it worked for me.. I am facing problem when using User identity while building windows 2019 image. I tried with various 2019 version from Marketplace but no luck. Also, Windows Update goes into infinite loop with RPC communication failure.

Here is what i am trying to do with your existing template: 
Stage file from storage container to VM drive and have noticed the entire packer process crashes when trying to build image at the very end after waiting for hour. Also, when I use windows-update, RPC communication fails. I noticed this when using user identity.

Do you have some samples for Windows 2016 or 2019 image build using user identity? 

Here are the sample i am trying to use in customize?

	{
                            "type": "PowerShell",
                            "name": "buildArtifactsdir",
                            "runElevated": false,
                            "inline": [
                                "mkdir c:\\buildArtifacts"
                            ]
                        },
                        {
                            "type": "File",
                            "name": "postConfig",
                            "sourceUri": "https://storageaccount.blob.core.windows.net/container/win2019.ps1",
                            "destination": "c:\\buildArtifacts\\win2019.ps1"
                        }

**Comment by sajithvasu** [comment]
@danielsollondon : It would be great if you can give some sample for windows using User Identity for staging file using something like this - 

 "customize": [ 
         { 
            "type": "File", 
             "name": "<name>", 
             "sourceUri": "<source location>",
             "destination": "<destination>",
          }
     ]

**Comment by drewkg** [comment]
@danielsollondon this sounds similar to the issue reported in #28 , if you reach out to me directly happy to walk you through a complete sample using a MSI to retrieve from a storage account (this bit does actually work well) or to test any solution.

**Comment by sajithvasu** [comment]
@drewkg : Thanks for responding! Can you send me the sample if you have any? I see using MSI, files do get upload to the Image as per the customization.log from packer but packer build never completes successfully. It fails after the long wait. Same template works fine if i remove user identity and storage account reference.

**Comment by danielsollondon** [comment]
Thanks @drewkg  for helping out here too,  @sajithvasu can you send me your steps (inc template minus sensitive contents) and the full customization.log to danis@microsoft.com

**Comment by danielsollondon** [comment]
Quick update, there is an open issue with w2019, we are working to resolve this asap, tracking in #28.

**Comment by sajithvasu** [comment]
Thanks @danielsollondon ! I will test the user identity with windows 2016 to see if that is successful.

**Comment by sajithvasu** [comment]
@danielsollondon : I see the same behavior with 2016 windows. 
Here is the source: 
    "source": {
                        "type": "PlatformImage",
                        "publisher": "MicrosoftWindowsServer",
                        "offer": "WindowsServer",
                        "sku": "2016-Datacenter",
                        "version": "2016.127.20190603"
                    },

The error invoke command gave is "ERROR: Deployment failed. Correlation ID: <some guid>. Internal error occurred." 

Last few lines of the customization.log. I removed the id and kept the message:

 PACKER ERR 2020/04/23 17:28:31 machine readable: azure-arm,artifact []string{"1", "builder-id", ""}
 PACKER ERR 2020/04/23 17:28:31 machine readable: azure-arm,artifact []string{"1", "id", ""}
 PACKER ERR 2020/04/23 17:28:31 machine readable: azure-arm,artifact []string{"1", "string", ""}
 PACKER ERR 2020/04/23 17:28:31 machine readable: azure-arm,artifact []string{"1", "files-count", "0"}
 PACKER ERR 2020/04/23 17:28:31 machine readable: azure-arm,artifact []string{"1", "end"}
Done exporting Packer logs to Azure for Packer prefix:  PACKER OUT
 PACKER ERR 2020/04/23 17:28:31 [INFO] (telemetry) Finalizing.
 PACKER ERR 2020/04/23 17:28:31 waiting for all plugin processes to complete...
 PACKER ERR 2020/04/23 17:28:31 /bin/packer: plugin process exited
 PACKER ERR 2020/04/23 17:28:31 /bin/packer: plugin process exited
 PACKER ERR 2020/04/23 17:28:31 /bin/packer: plugin process exited
 PACKER ERR 2020/04/23 17:28:31 /bin/packer: plugin process exited
 PACKER ERR 2020/04/23 17:28:31 /bin/packer: plugin process exited
 PACKER ERR 2020/04/23 17:28:31 /bin/packer: plugin process exited
Done exporting Packer logs to Azure for Packer prefix:  PACKER ERR

**Comment by sajithvasu** [comment]
I have tried on rhel 7.7 and it fails.. I think User identity with Packer does not work.

**Comment by danielsollondon** [comment]
Hi @sajithvasu  - I just dropped you a mail, can you send me your customization.log

**Comment by sajithvasu** [comment]
@danielsollondon : Thank you ! Shared info over the email..

**Comment by danielsollondon** [comment]
Apologies for the inconvenience, please see #31 for progress/tracking.

**Comment by danielsollondon** [comment]
closing, as duplicate
