### ISSUE TITLE
customize inline scripts do not get executed!

### ISSUE THREAD

**Issue by ehab2012** [danielsollondon/azvmimagebuilder#33]
hi

I am trying the example on

[1_Azure_DevOps](https://github.com/danielsollondon/azvmimagebuilder/tree/master/solutions/1_Azure_DevOps)

the release pipeline Succeeded, then vm image is created, files are baked in but looks like the PowerShell-customize inline scripts do not get executed at all!

am i missing some step?

any help will be very much appreciated. 

Thank you and regards
ehab

**Comment by danielsollondon** [comment]
Hi @ehab2012 sorry you are having these issues. Can you share more details, such as the source image? Are you just just trying the end to end example? If so, can you confirm the inline scripts you are using (please omit sensitive code). To troubleshoot this, you can add a sleep into the inline script, Start-Sleep -s 1200, then once the task is waiting, you can go to the portal, find the IT_t_* resource group, Storage Account > Blobs > packerlogs > click on the directory > customization.log. If that does not help, please send me the customization.log, danis@microsoft.com.

**Comment by danielsollondon** [comment]
Hi @ehab2012 - I have not heard from you, I will close the issue temporarily until I get an email.
