### ISSUE TITLE
Windows Update does not work in devops

### ISSUE THREAD

**Issue by pcdiks** [danielsollondon/azvmimagebuilder#34]
[customization 5.log](https://github.com/danielsollondon/azvmimagebuilder/files/4567592/customization.5.log)
I created a project in devops and use the image builder agent task to integrate with azure image builder. The project works fine with the Windows10-Ehv master image. But when I tick the windows update checkbox the build fails with a timeout. Tried multiple times but that checkbox makes it fail.

**Comment by danielsollondon** [comment]
Hi @pcdiks - I will check the log on Monday, we have seen occasionally Windows Update is exhausting the resources on our Default VM size, D1_V2, in the devOps task, it may be worth trying to increase the VM Size to a D2_V2?

**Comment by pcdiks** [comment]
I already configured it to use a Standard_D2_v2 vm...

**Comment by pcdiks** [comment]
Did you find anything?

**Comment by danielsollondon** [comment]
@pcdiks - I did take a quick look, but I need to do some more investigations, I will come back to you today.

**Comment by danielsollondon** [comment]
@pcdiks - when I look in the log, I see the Windows Update failing:
**RPC endpoint: Communicator ended with: 101**
When I tried the build in devOps using the same base image, with one file customization, the win update ran ok. I see before win update you are installing chocolatey, what are you using chocolatey to install/configure?
I looked up the error you are seeing, and there is this issue, https://github.com/rgl/packer-provisioner-windows-update/issues/37, can you take a look, and see if any of it applies to this scenario?

**Comment by pcdiks** [comment]
Installing chocolaty was to see if I could install Brave for everyone but that does not work. I removed it from the code and will try the build again. I will read the article and see if it has a solution for my problem.

**Comment by pcdiks** [comment]
Also without chocolaty it keeps failing if I enable Windows Updates.

**Comment by danielsollondon** [comment]
Hi @pcdiks - I want to try and get you resolved, can you email me, so I can understand what you are doing more please, danis@microsoft.com.

**Comment by pcdiks** [comment]
Done

**Comment by pcdiks** [comment]
I switched to Jenkins for now.

**Comment by danielsollondon** [comment]
Apologies for this @pcdiks, we could not identify the issue, if you see this again, please let me know.
