### ISSUE TITLE
Unable to delete imageTemplate

### ISSUE THREAD

**Issue by gmyx** [danielsollondon/azvmimagebuilder#38]
Don't know if the is the correct place to put this. I've been trying to use the imageBuilder. I've written a script based on your quick quickStarts. I am trying to delete the created imageTemplate but it refuses. There are no other resources other than his template and resource group.

```
Remove-AzResource : {
  "code": "OperationNotAllowed",
  "message": "Operation 'Microsoft.VirtualMachineImages/imageTemplates/delete' is not allowed in provisioningState: 'provisioned', runState: 'running'"
 }
CorrelationId: {redacted}
At line:1 char:1
+ Remove-AzResource -ResourceId "/subscriptions/{redacted} ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.RemoveAzureResourceCmdlet
```

**Comment by danielsollondon** [comment]
You cannot delete an image template whilst the build is running. Is you aim to cancel an existing build?

If so, that functionality will be with us at the end of the month.

**Comment by gmyx** [comment]
I will wait for the ability to cancel. The resource is stuck in this state - the target resources were deleted while it was in process and never errored out.

**Comment by danielsollondon** [comment]
Hi @gmyx - cancel functionality is now available: https://github.com/danielsollondon/azvmimagebuilder#cancel-a-running-build

**Comment by gmyx** [comment]
Thank! I tried it and now its stuck in cancelling (over 12 hours now). But the cancel started.
