### ISSUE TITLE
Virtual network parameters/properties for AIB template

### ISSUE THREAD

**Issue by tbeavers** [danielsollondon/azvmimagebuilder#4]
Hi Daniel,

I am trying to use an existing virtual network rather than setup a new when creating my image template, but am unsure of the network parameter/property names to use in my template file.

For example, when creating a template with packer, I use the following parameter names under builders:

"virtual_network_name"
"virtual_network_resource_group_name"
"virtual_network_subnet_name"

Do you happen to know the equivalent parameter names to use under properties in an AIB template file?

Any help would be gratefully appreciated.

Thanks in advance for your support,

Terry

**Comment by tbeavers** [comment]
Hi Daniel,
Thanks for the quick response.  Was really hoping you had something available for AIB.  We are able to do this using packer, but we are having issues trying to add the VM and users to a domain with packer and was hoping we could get everything setup with AIB.

Guess we will stay tuned for updates on these parameters and if by chance you know a way to successfully add a VM and users to a domain, please let me know.

Thanks for your support,

Terry

**Comment by danielsollondon** [comment]
Terry - I will keep you up to date, I will comeback in a 3 - 4 weeks with a more concrete update.

**Comment by danielsollondon** [comment]
hi @tbeavers - this is now resolved, we have implemented the functionality:
https://github.com/danielsollondon/azvmimagebuilder/blob/master/aibNetworking.md

Thanks!
