### ISSUE TITLE
Add possibility to set the image version name when distributing to Azure Shared Gallery

### ISSUE THREAD

**Issue by cbroglia** [danielsollondon/azvmimagebuilder#41]
Hello, I'm distributing from Image Builder to a Shared Image Gallery. The Image name seems is not possible to be set. Currently, the image is named with something like "0.24254.42935" or "0.24254.53522". 
To have proper versioning, it is needed to be able to set the name, so to name each version like "0.0.1". 
I have checked the latest version of the schema here (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/imagebuilder/resource-manager/Microsoft.VirtualMachineImages/stable/2020-02-14/imagebuilder.json) but also there I do not see a way, inside the "SharedImage" item of the "distribute" section, a property to set to configure this value. 

Here an example of the bad naming on how images end up inside the Image definition.

![Imageversion](https://user-images.githubusercontent.com/25897219/82089778-912c2f00-96f4-11ea-8b53-04b933dacfad.png)

**Comment by danielsollondon** [comment]
Great feedback @cbroglia, this is coming at the end of the month, stay tuned!

**Comment by danielsollondon** [comment]
@cbroglia - this is available now.

https://github.com/danielsollondon/azvmimagebuilder#support-for-more-shared-image-gallery-sig-properties
