### ISSUE TITLE
The WindowsUpdate provisioner goes into a loop 

### ISSUE THREAD

**Issue by cbroglia** [danielsollondon/azvmimagebuilder#42]
I've included the WindowsUpdate provisioner for patching a Windows 10 multisession 1909 virtual machine. Of the ten launches I've done, only once it finished successfully, all the other times it goes into a loop. See the attached extract of the customization.

[customization - extract.log](https://github.com/danielsollondon/azvmimagebuilder/files/4645383/customization.-.extract.log)
log

**Comment by danielsollondon** [comment]
Hi @cbroglia - a huge apology for getting to this just now, is this issue this happening?

**Comment by cbroglia** [comment]
Yes, it's not a 100% chance of getting stuck, of the 30 runs I have done it went through normally 3 or 4 times, the other times I had to click "Restart" from the Azure portal.

**Comment by tlilly2010** [comment]
I am experiencing the same thing, and it appears to have started failing completely (at least for me) with the 20h1 base image.

**Comment by danielsollondon** [comment]
Hi @tlilly2010, @cbroglia - I have looked into it, but would you both be able to raise a support case please? When you raise the ticket, can you select **Product Family: Azure, Product: Virtual Machine Running Windows, Support Topic: Management, Support Subtopic: Issues with Azure Image Builder.**

Once you have raised the ticket, can you email me the case numbers, danis@microsoft.com

**Comment by danielsollondon** [comment]
please reopen if still seeing an issue.
