### ISSUE TITLE
27th May 2020 Update - NEW API VERSION ‘2020-02-14’

### ISSUE THREAD

**Issue by danielsollondon** [danielsollondon/azvmimagebuilder#46]
In preparation for GA, the AIB team is now releasing more features, starting with a new API version.

**Actions Required**
Please review the documentation for the latest API version, and take action for these breaking changes:
1.	identity is a mandatory requirement, please review the May Service Update document, on how to add this to your templates.
2.	vnetConfig - this specification is changing, from providing, name, subnetName, resourceGroupName to just subnetId, you will need to update you JSON template and create a new AIB template.
3.	Review steps for operating and maintaining image templates created with the previous API version, and what will happen with new templates created.

For details see [here](https://github.com/danielsollondon/azvmimagebuilder#27th-may-2020-update---new-api-version---action-required)

**FAQs**
•	What about the AIB Azure DevOps? - The DevOps task is hard coded to use an API version, this will be updated, but continue to work without interuption.
•	When will we announce the new functionality? - The new features will be documented by 28th May
•	Can I use existing documentation? - Yes, examples that have breaking changes will be updated.

**Comment by ld0614** [comment]
Since the updates started at approximately 0700 PST on the 26th I've not been able to successfully deploy my Image Builder Template.  The error message I receive is:

```
11:55:15 - Resource Microsoft.VirtualMachineImages/imageTemplates 'TestImage1909' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "InternalOperationError",
        "message": "Internal error occurred. This is a generic error. To identify possible causes, go to https://aka.ms/azvmimagebuilderts."
      }
    ]
  }
}'
```

This could well be a mistake in my template but I'm not sure where to look for accurate errors as the template itself is accepted.  I also noticed that the aka link in the error message looks like it has a typo

**Comment by ld0614** [comment]
I identified the above issue, it was related to the User Identity not having permissions on the storage account for customization scripts.  Having a more useful error would have saved significant time though 😄

**Comment by danielsollondon** [comment]
@ld0614 - thanks for letting me know, apologies I am late to the game here.

**Comment by danielsollondon** [comment]
Hi @ld0614 - we have been rolling out a lot of more descriptive errors, you should see these coming through now. Please raise an issue if you seen further instances. Thank you!

**Comment by poochwashere** [comment]
Hello, I am getting the `generic` error as well. I do not think it is due to the SP access level to the `storage account` however.
```
(⎈ |dev-kube09-admin:kube-system)
ansible ❯ az resource invoke-action \
     --resource-group $imageResourceGroup \
     --resource-type  Microsoft.VirtualMachineImages/imageTemplates \
     -n devopsAgentImg-v0.1 \
     --action Run
Deployment failed. Correlation ID: aa84f84e-2b4c-4a68-95ca-2ac5cc2f8855. Internal error occurred. This is a generic error. To identify possible causes, go to https://aka.ms/azvmimagebuilderts.
``` 
Also note that the URL provided https://aka.ms/azvmimagebuilderts (as of yesterday) takes you to a landing page advertising the new Surface Pro :)
