### ISSUE TITLE
Delete command failed with http error code: 405

### ISSUE THREAD

**Issue by rihago** [danielsollondon/azvmimagebuilder#48]
trying to delete my template.
first did a cancel command. but now its stuck.

Operation Microsoft.VirtualMachineImages/imageTemplates/delete is not allowed in provisioning state: provisioned or run state: canceling.

its in this state for about 19 hours.

Does the canceling timeout? so i can delete the template. or can i force delete it?

**Comment by drewdavis1** [comment]
I'm also experiencing the same issue.

**Comment by danielsollondon** [comment]
Hi @rihago , @drewdavis1 - Apologies for the late reply, can I clarify how you are hitting this issue?
The build is running, you cancel, then you try to delete, but when you try to delete, the cancelling state does not allow the delete?

**Comment by rihago** [comment]
Hi @danielsollondon thats correct.

as of now its still running the cancel.

getting this error:

**Comment by danielsollondon** [comment]
@rihago , can you email me your support case number, and I will follow up, danis@microsoft.com?

**Comment by rihago** [comment]
@danielsollondon i've mailed you the case number.

**Comment by danielsollondon** [comment]
@rihago - please can you resend the email, I can't see it. I did test the cancel too, but I could not reproduce the issue you are seeing, so I want to understand what's happening in your environment.

**Comment by danielsollondon** [comment]
please reopen if seeing an issue still.

**Comment by modios** [comment]
Same issue. I contacted support, but also comment here because it seems that there are still issues with this. 
Cannot delete template because "state: canceling". It's just stack in this state and cannot delete the resource. 
I assume at some point you should able to force delete or force cancel, time out.
