### ISSUE TITLE
400 The SSL Certificate Error

### ISSUE THREAD

**Issue by birdnathan** [danielsollondon/azvmimagebuilder#51]
Receiving this error when trying to deploy a AIB Template......this was working without issue last week. Any ideas? Nothing else to go on.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"BadRequest\",\r\n \"message\": \"<html>\\r\\n<head><title>400 The SSL certificate error</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>400 Bad Request</h1></center>\\r\\n<center>The SSL certificate error</center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n\"\r\n }\r\n}"}]}

![image](https://user-images.githubusercontent.com/42775203/84690737-dd100500-af3a-11ea-902b-c33019932974.png)

**Comment by danielsollondon** [comment]
@birdnathan - I will forward this to the dev team, and come back to you.

**Comment by danielsollondon** [comment]
@birdnathan - can you share the region please?

**Comment by danielsollondon** [comment]
@birdnathan - we identified the issue, can you retry please?

**Comment by birdnathan** [comment]
@danielsollondon My region was West Europe and all is working again. Thanks
