### ISSUE TITLE
Update Time Zone

### ISSUE THREAD

**Issue by tikicoder** [danielsollondon/azvmimagebuilder#53]
We have tried a few ways to update the timezone, but it keeps defaulting back to UTC. 
We even tried the following customizer.

{
            “type”: “PowerShell”,
            “name”: “settingUpMgmtAgtPath”,
            “runElevated”: true,
            “inline”: [
              “mkdir c:\\buildActions1”,
              “Set-TimeZone -Id ‘US Mountain Standard Time’“,
              “echo Azure-Image-Builder-Was-Here  > c:\\buildActions1\\buildActionsOutput.txt”
            ]
          }

**Comment by danielsollondon** [comment]
Hi @tikicoder - I would suggest raising a [support case](https://github.com/danielsollondon/azvmimagebuilder/blob/master/troubleshootingaib.md#troubleshooting-azure-vm-image-build-aib-failures)., as AIB will set this, but I am not sure what happens when the VM is deployed.
