### ISSUE TITLE
Quickstart is broken: following the "existingVNETWindows" tutorial, the image never builds

### ISSUE THREAD

**Issue by MostlyArmless** [danielsollondon/azvmimagebuilder#55]
Following [your quickstart documentation](https://github.com/danielsollondon/azvmimagebuilder/tree/master/quickquickstarts/1a_Creating_a_Custom_Win_Image_on_Existing_VNET), I made the necessary modifications to the scripts to use my existing vnet name etc, but every time I get to the "Build the image" step (where you're supposed to run `Invoke-AzResourceAction`) it always fails to build.

If I try to proceed to the VM deployment step anyways, it fails there too, indicating that the image is definitely not getting built successfully.

I'm running this in a Trial Azure subscription. I can provide all my source code (modified copies of the scripts from the quickstart), just let me know what's needed.

**Comment by danielsollondon** [comment]
@MostlyArmless  - Apologies, I will check this out.

**Comment by danielsollondon** [comment]
@MostlyArmless, apologies, I have not been able to get to this yet, I am OOF for 1 week now, and will get to it then. If you need support sooner, please raise a [support case](https://github.com/danielsollondon/azvmimagebuilder/blob/master/troubleshootingaib.md#troubleshooting-azure-vm-image-build-aib-failures).

**Comment by danielsollondon** [comment]
@MostlyArmless - thank you for bringing this to my attention, this has been fixed.
