### ISSUE TITLE
The Azure VM Image Builder DevOps Task Timeout on Windows Update

### ISSUE THREAD

**Issue by baltic-dev** [danielsollondon/azvmimagebuilder#58]
I am using the image builder DevOps extention and when I create a release with the Windows update option enable the build times out whilst completing the updates with the following error every time.

##[error]Error: post template call failed for template t_122_1595003222849 with error: Failed in distributing 1 images out of total 1: Some error happened, please check the error details. (CODE: 200)

**Comment by danielsollondon** [comment]
Hi, without seeing the details, I cannot comment, however, we have seen this before with a [1hour](https://github.com/danielsollondon/azvmimagebuilder/blob/master/troubleshootingaib.md#devops-task), please take a look.

The Windows Update option can add reboots, slowing down the build time too.

If you cannot resolve yourself, please raise a [support case](https://github.com/danielsollondon/azvmimagebuilder/blob/master/troubleshootingaib.md#troubleshooting-azure-vm-image-build-aib-failures).
