### ISSUE TITLE
error

### ISSUE THREAD

**Issue by prakashraaj046** [danielsollondon/azvmimagebuilder#6]
![image](https://user-images.githubusercontent.com/54060781/65433691-18155a00-de3b-11e9-834e-57ec811eb7a3.png)

This is the error i'm getting on starting the image build for Create a Windows Custom Image from an Azure Platform Vanilla OS Image

**Comment by danielsollondon** [comment]
Have you checked the customization.log? Can you see any errors in there?

**Comment by prakashraaj046** [comment]
Nope. I don't see any errors corresponding to it

**Comment by prakashraaj046** [comment]
![image](https://user-images.githubusercontent.com/54060781/65481624-9ca3bf00-deb3-11e9-9fe9-db3ae137500f.png)
This is what it displays when i clicked in the link

**Comment by danielsollondon** [comment]
Hi - would you be able to send me the customization.log, your SubID, and RG Name, to danis@microsoft.com

**Comment by prakashraaj046** [comment]
Hi Daniel, 
I tried the all the steps in Azure portal by,
 1. Creating a managed image from a VM by generalizing it
 2. Creating a shared image gallery
 3. Creating a Image definition in the shared image gallery and a new version of a image by using the managed image as base image.
 4. Once the new image version is created,
 5. I can create a VM using the new image version.
This method doesn't require any sevice principal or app registration of any matter.
Is this the correct procedure?

**Comment by danielsollondon** [comment]
That looks like the correct steps, as you are doing this, you have the right permissions, if you want image builder to inject a new version, then you must grant the SPN contributor rights on the shared image gallery resource group. If you want image builder to use the that image version as a source, the SPN needs reader permissions on it.

**Comment by prakashraaj046** [comment]
I'll try this or and hey back to you.. Thanks for your patience and advice

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by danielsollondon** [comment]
@prakashraaj046 - just checking in, did setting up the perms work?

**Comment by prakashraaj046** [comment]
Is it possible to use a version of image I created from image gallery as a base image?
Everytime I try this it shows the managed
image for suggestions for base image

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by prakashraaj046** [comment]
Perms work?

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by danielsollondon** [comment]
Hi,
Sorry for the delay, currently you cannot set the SIG Version for the image that image builder creates, this is on the the roadmap, I would think early 2020. In the meantime, you can emit a managed image and inject that into the SIG, passing all the params you want to specify, such as version. Does that help?

Thanks,

**Comment by prakashraaj046** [comment]
Yeah that'll work.
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by danielsollondon** [comment]
Thanks for the confirmation.
