### ISSUE TITLE
Issue in Invoking method on Import mudule

### ISSUE THREAD

**Issue by bhupi123** [danielsollondon/azvmimagebuilder#60]
Hi

I am importing a module https://gallery.technet.microsoft.com/scriptcenter/Grant-Revoke-Query-user-26e259b0
during PS script execution on windows. Module is working fine if I execute my PS script directly on Windows Datacenter 2019  but failing with below exception if executed through pipeline.

Exception calling "RemovePrivilege" with "2" argument(s): "The system cannot find the file specified" [b3f571e4-459e-42f3-8e19-51233538c8a9] PACKER OUT ==> azure-arm: At C:\Users\packer\UserRights.psm1:675 char:77 [b3f571e4-459e-42f3-8e19-51233538c8a9] PACKER OUT ==> azure-arm: + ... ($Acct, "Revoke $Priv right")) { $lsa.RemovePrivilege($Acct,$Priv) }

I tried changing name of method RemovePrivilege as mentioned in link https://gallery.technet.microsoft.com/scriptcenter/Grant-Revoke-Query-user-26e259b0/view/Discussions/3 but no success.
I tried by downloading file and then importing in my PS script and by giving it hardcoded path (C:\buildartifacts\windows-image\UserRights.psm1) to import as well, always end with same exception. It happens only when I execute script through Pipeline task
 
Thanks

**Comment by danielsollondon** [comment]
@bhupi123 - sorry, I only just saw this. Can you raise a [support ticket](https://github.com/danielsollondon/azvmimagebuilder/blob/master/troubleshootingaib.md#troubleshooting-azure-vm-image-build-aib-failures), and we will assist you.

**Comment by danielsollondon** [comment]
@bhupi123 - did you raise a support ticket, and was this resolved?

**Comment by bhupi123** [comment]
Sorry for late reply. Weird things happened.

This is giving issue.

Revoke-UserRight -Account "S-1-1-0" -Right SeNetworkLogonRight # It will Revoke Eveyone
Grant-UserRight -Account "Guest" -Right SeDenyNetworkLogonRight
Revoke-UserRight -Account "Guest" -Right SeNetworkLogonRight

if I do this then it works fine

Grant-UserRight -Account "Guest" -Right SeDenyNetworkLogonRight
Revoke-UserRight -Account "S-1-1-0" -Right SeNetworkLogonRight # It will Revoke Eveyone
Revoke-UserRight -Account "Guest" -Right SeNetworkLogonRight

Which is very strange to me.
