### ISSUE TITLE
Windows Update stuck in loop - wont complete

### ISSUE THREAD

**Issue by danielmarker** [danielsollondon/azvmimagebuilder#70]
After seeing the latest issue resolved - trying to build a VM afresh in West Europe - no inline script we seem to get stuck in this loop:

![image](https://user-images.githubusercontent.com/8668101/91299572-c0dddf00-e799-11ea-8c70-ca9697349a0c.png)

Last time this timed out after 4 hours?

**Comment by danielsollondon** [comment]
Hi @danielmarker - please can you open a [support case](https://github.com/danielsollondon/azvmimagebuilder/blob/master/troubleshootingaib.md#troubleshooting-azure-vm-image-build-aib-failures), and we will investigate.

**Comment by danielmarker** [comment]
@danielsollondon  - we opened a support call and Premier Support said "they dont support it" - 120082725002776 was the ticket number...
