### ISSUE TITLE
Azure DevTest Labs

### ISSUE THREAD

**Issue by DanielBrown-ranger1968** [danielsollondon/azvmimagebuilder#73]
A question I have is why is there a need for AIB when it seems to be duplicating the functionality of [Azure DevTest Labs](https://docs.microsoft.com/en-us/azure/devtest-labs/devtest-lab-overview) (DTL)?

All of the elements on AIB already exist in DTL and it has a UI to manage it in the portal as well as [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/lab?view=azure-cli-latest) and [Powershell](https://github.com/Azure/azure-devtestlab/tree/master/samples/DevTestLabs/Modules/Library) support for scripting.

DTL also in supports integration with GitHub for custom artifacts (customizers in AIB) as well as Shared Image Gallery.

DTL already has the infrastructure to handle management of images and deployment/lifecycle of VMs.

**Comment by danielsollondon** [comment]
@DanBrown-TechSmith - sorry, I have not replied sooner, I will reply this week.

**Comment by asumner** [comment]
@DanBrown-TechSmith I've just started to use AIB and already I'm starting to believe it has no commitment or long term support? Is this now deprecated?

@danielsollondon I think its been over a week, I hope you and your family are safe and well 👍
