### ISSUE TITLE
Getting error during image build

### ISSUE THREAD

**Issue by balaji2219** [danielsollondon/azvmimagebuilder#74]
Hi,

We are getting below error when the job tries to download files from azure storage for windows image build. It works fine for our Linux image builds.

[a427b39a-8160-4e19-86a6-8d46cca24fd4] PACKER OUT ==> azure-arm: Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.
[a427b39a-8160-4e19-86a6-8d46cca24fd4] PACKER OUT ==> azure-arm: At C:\Windows\Temp\script-5f4fa0b3-ec00-e090-6091-edb5594816b8.ps1:2 char:1
[a427b39a-8160-4e19-86a6-8d46cca24fd4] PACKER OUT ==> azure-arm: + Invoke-WebRequest -Uri 'https://bala2219StorageAccount.blob.core.windows. ...
[a427b39a-8160-4e19-86a6-8d46cca24fd4] PACKER OUT ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[a427b39a-8160-4e19-86a6-8d46cca24fd4] PACKER OUT ==> azure-arm:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
[a427b39a-8160-4e19-86a6-8d46cca24fd4] PACKER OUT ==> azure-arm:    eption
[a427b39a-8160-4e19-86a6-8d46cca24fd4] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by danielsollondon** [comment]
Hi @balaji2219 - sorry, I did not see this earlier, please raise a [support incident](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#getting-support) and the specialist AIB support team will address this. If you are still having issues, please reopen.
