### ISSUE TITLE
some inline powershell commands are not executed

### ISSUE THREAD

**Issue by balaji2219** [danielsollondon/azvmimagebuilder#75]
Hi Team,

In our windows image releases, some commands are not executed, even though the log first says it found commands. e.g. it says found command msiexec.exe, but its not executed.
------------------------
Below are the commands I am giving:
cd 'c:\buildArtifacts\Rapid7-Agent-Windows'
msiexec.exe /i agentInstaller-x86_64.msi /quiet
Stop-Service  ir_agent
Remove-Item -Path 'C:\program Files\Rapid7\Insight Agent\components\bootstrap\common\bootstrap.cfg' -Force
cd c:\
Remove-Item -Path 'c:\buildArtifacts' -Force -Recurse
-----------------------
Below is the log.

[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 [INFO] (telemetry) Starting provisioner powershell
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: New-item -Path c:\buildartifacts -itemtype directory
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: Invoke-WebRequest -Uri 'https://Myteststorageaccount.blob.core.windows.net/imagebuilder-vststask/Rapid7-Agent-Windows/1936-1/Rapid7-Agent-Windows_1599565267468.zip?[REDACTED] -OutFile c:\buildartifacts\Rapid7-Agent-Windows.zip -UseBasicParsing
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: Expand-Archive -Path c:\buildartifacts\Rapid7-Agent-Windows.zip -DestinationPath c:\buildartifacts\Rapid7-Agent-Windows
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: cd 'c:\buildArtifacts\Rapid7-Agent-Windows'
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: msiexec.exe /i agentInstaller-x86_64.msi /quiet
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: Stop-Service  ir_agent
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: Remove-Item -Path 'C:\program Files\Rapid7\Insight Agent\components\bootstrap\common\bootstrap.cfg' -Force
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: cd c:\
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command: Remove-Item -Path 'c:\buildArtifacts' -Force -Recurse
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Found command:
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Opening /tmp/powershell-provisioner305978697 for reading
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5f576e05-d2be-8210-d4b9-cf31e247d604.ps1
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-provisioner-powershell plugin: [INFO] 74 bytes written for 'uploadData'
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 [INFO] 74 bytes written for 'uploadData'
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:29 packer-builder-azure-arm plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5f576e05-d2be-8210-d4b9-cf31e247d604.ps1'
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:30 packer-builder-azure-arm plugin: #< CLIXML
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:30 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:30 packer-provisioner-powershell plugin: [INFO] 822 bytes written for 'uploadData'
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:31 [INFO] 822 bytes written for 'uploadData'
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:31 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Uploading file to 'c:/Windows/Temp/script-5f576e05-a216-d079-19c9-63c0cef6670b.ps1'
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:32 packer-builder-azure-arm plugin: #< CLIXML
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:33 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
[e5980613-e076-4723-8d06-5e047c11043c] PACKER ERR 2020/09/08 11:46:33 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>[INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5f576e05-d2be-8210-d4b9-cf31e247d604.ps1; &'c:/Windows/Temp/script-5f576e05-a216-d079-19c9-63c0cef6670b.ps1'; exit $LastExitCode }"
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: New-item : An item with the specified name C:\buildartifacts already exists.
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: At C:\Windows\Temp\script-5f576e05-a216-d079-19c9-63c0cef6670b.ps1:1 char:1
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + New-item -Path c:\buildartifacts -itemtype directory
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:     + CategoryInfo          : ResourceExists: (C:\buildartifacts:String) [New-Item], IOException
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: Stop-Service : Cannot find any service with service name 'ir_agent'.
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: At C:\Windows\Temp\script-5f576e05-a216-d079-19c9-63c0cef6670b.ps1:6 char:1
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + Stop-Service  ir_agent
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:     + CategoryInfo          : ObjectNotFound: (ir_agent:String) [Stop-Service], ServiceCommandException
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.StopServiceCommand
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: Remove-Item : Cannot find path 'C:\program Files\Rapid7\Insight Agent\components\bootstrap\common\bootstrap.cfg'
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: because it does not exist.
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: At C:\Windows\Temp\script-5f576e05-a216-d079-19c9-63c0cef6670b.ps1:7 char:1
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + Remove-Item -Path 'C:\program Files\Rapid7\Insight Agent\components\b ...
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:     + CategoryInfo          : ObjectNotFound: (C:\program File...n\bootstrap.cfg:String) [Remove-Item], ItemNotFoundEx
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:    ception
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: Remove-Item : Cannot remove item C:\buildArtifacts\Rapid7-Agent-Windows: The process cannot access the file
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: 'C:\buildArtifacts\Rapid7-Agent-Windows' because it is being used by another process.
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: At C:\Windows\Temp\script-5f576e05-a216-d079-19c9-63c0cef6670b.ps1:9 char:1
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + Remove-Item -Path 'c:\buildArtifacts' -Force -Recurse
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:     + CategoryInfo          : WriteError: (Rapid7-Agent-Windows:DirectoryInfo) [Remove-Item], IOException
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: Remove-Item : Cannot remove item C:\buildArtifacts: The directory is not empty.
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: At C:\Windows\Temp\script-5f576e05-a216-d079-19c9-63c0cef6670b.ps1:9 char:1
[e5980613-e076-4723-8d06-5e047c11043c] PACKER OUT ==> azure-arm: + Remove-Item -Path 'c:\buildArtifacts' -Force -Recurse

**Comment by danielsollondon** [comment]
Hi @balaji2219 - sorry, I did not see this earlier, please raise a [support incident](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#getting-support) and the specialist AIB support team will address this.
