### ISSUE TITLE
Request:  Example of importing Packer scripts

### ISSUE THREAD

**Issue by larryclaman** [danielsollondon/azvmimagebuilder#77]
The Azure [documentation ](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-overview)for AIB says:
_Because the Image Builder is built on HashiCorp Packer, you can also import your existing Packer shell provisioner scripts_

However, I cannot find any examples of how to import Packer provisioner scripts, either in the Azure docs or in this gallery.
Could you include this as one of the examples?

**Comment by danielsollondon** [comment]
Hi @larryclaman - sorry for the delay, the sentence means that if you are referencing scripts or inline commands in Packer shell provisioner you can use them immediately with AIB, it does'nt mean we support import whole Packer Provisioner configurations, though, that is on the backlog. Apologies if this is what you thought, I will evaluate the docs and reword.

**Comment by kengaul** [comment]
I think even that is misleading...If you have built your scripts in such a way that they don't rely on the packer way of doing things with environment clauses etc then you can probably reuse packer scripts but those will likely few or even only inline scripts.

Had a go at trying convert https://github.com/actions/virtual-environments for a self hosted DevOps build agent pool to AIB and the differences between actual packer and image builder make it an almost complete re-write with virtually nothing reusable. Not sure that backlog item will ever see the light of day and the documentation should be updated to make it clear that while it might be packer under the hood and there may be some portability the JSON constructs and capability abstraction means there is limited instant reuse.

Unless I'm really missing something obvious that makes this easier than it appears to be?

**Comment by danielsollondon** [comment]
Hi @kengaul - thanks for this letting me know your thoughts, I have reworded the documentation, it is in review now.
