### ISSUE TITLE
Update Failing on 2016 and 2012

### ISSUE THREAD

**Issue by bhupi123** [danielsollondon/azvmimagebuilder#78]
For me windows update is failing with version 2016 and 2012 ,Its working on 2019 Version,I tried Increasing Size of Machine but no benefit

**Comment by danielsollondon** [comment]
Hi @bhupi123 - sorry, I did not see this earlier, please raise a [support incident](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#getting-support) and the specialist AIB support team will address this.
