### ISSUE TITLE
cancel not working

### ISSUE THREAD

**Issue by BladeFireLight** [danielsollondon/azvmimagebuilder#79]
Remove-AzResource  -ResourceGroupName 'uswc-WVD-Shared-rg' -ResourceName 'wvdUser0' -ResourceType Microsoft.VirtualMachineImages/imageTemplates

Remove-AzResource: {
  "code": "OperationNotAllowed",
  "message": "Operation Microsoft.VirtualMachineImages/imageTemplates/delete is not allowed in provisioning state: provisioned or run state: running."
 }

Invoke-AzResourceAction  -ResourceGroupName 'uswc-WVD-Shared-rg' -ResourceName 'wvdUser0' -ResourceType Microsoft.VirtualMachineImages/imageTemplates -Action Cancel -force -ApiVersion '2020-02-14'

Invoke-AzResourceAction: {
  "code": "OperationNotAllowed",
  "message": "Operation Microsoft.VirtualMachineImages/imageTemplates/cancel/action is not allowed in provisioning state: provisioned or run state: canceling."
 }

Remove-AzResource  -ResourceGroupName 'uswc-WVD-Shared-rg' -ResourceName 'wvdUser0' -ResourceType Microsoft.VirtualMachineImages/imageTemplates

Remove-AzResource: {
  "code": "OperationNotAllowed",
  "message": "Operation Microsoft.VirtualMachineImages/imageTemplates/delete is not allowed in provisioning state: provisioned or run state: canceling."
 }

it has been 6 hours and it still had not canceled.

**Comment by danielsollondon** [comment]
Hi @BladeFireLight - sorry, I did not see this earlier, please raise a [support incident](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#getting-support) and the specialist AIB support team will address this.
