### ISSUE TITLE
File customizer not placing file at destination path.

### ISSUE THREAD

**Issue by singhania** [danielsollondon/azvmimagebuilder#8]
Hi,
I am using multiple File customizer to place certain artifacts on the image.
But once i create a VM from created image, I could not find the artifact at destination location.
{
                "type": "File",
                "name": "downloadBuildArtifacts",
                "sourceUri": "https://raw.githubusercontent.com/danielsollondon/azvmimagebuilder/master/quickquickstarts/exampleArtifacts/buildArtifacts/index.html",
                "destination":"/tmp/index.html"
            },
            {
                "type": "File",
                "name": "sparkArtifact",
                "sourceUri": "https://xyz.blob.core.windows.net/imageartifact/abc.jar",
                "destination":"/tmp/abc.jar"
            },

**Comment by danielsollondon** [comment]
Hi, which OS are you using, some of the distro's will clear /tmp on reboot, I would suggest creating another directory another directory, and moving the files into that, let me know if that works.

**Comment by danielsollondon** [comment]
Please can you reopen if you are still seeing issues. thanks!
