### ISSUE TITLE
I am getting Below error for Images 2012, 2008. 2019 is working fine 

### ISSUE THREAD

**Issue by bhupi123** [danielsollondon/azvmimagebuilder#80]
Error: failed to get latest image version: request uri https://management.azure.com/subscriptions/XXXX/providers/Microsoft.Compute/locations/westeurope/publishers/MicrosoftWindowsServer/artifacttypes/vmimage/offers/WindowsServer/skus/2012/versions?$orderby=name%20desc&$top=1&api-version=2018-06-01: 

Artifact: VMImage was not found. (CODE: 404)

BTW Any Idea when AIB is released in Production.

**Comment by bhupi123** [comment]
I am waiting on this Please reply @danielsollondon

**Comment by danielsollondon** [comment]
@bhupi123 - please can you raise a support case, and share the ID here, we will triage it.
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#getting-support

**Comment by bhupi123** [comment]
Sorry to bother you , Image Id ,I was using wrong.
