### ISSUE TITLE
$subscriptionID

### ISSUE THREAD

**Issue by tsrob50** [danielsollondon/azvmimagebuilder#81]
The variable $subscriptionID is uses the PowerShell and CLI examples but the value is not defined in the examples.  The .json role templates are not updated properly because the value of the variable is null.

**Comment by danielsollondon** [comment]
Hi @tsrob50 - thanks for logging this, which examples are you referring to?

**Comment by tsrob50** [comment]
Honestly, No idea.  I went over so much documenting over the past two days I can't find what I was referencing.  If i find it again I'll be sure to get a link.  Sorry for not having the details, please close the issue.

**Comment by danielsollondon** [comment]
Np, let me know if you find it, and reopen.
