### ISSUE TITLE
How to add tags to Staging Resource Group while creating

### ISSUE THREAD

**Issue by ajayvarma560** [danielsollondon/azvmimagebuilder#85]
We are not able to create a staging resource group while running the AIB setup. This is because our organizational policies are stopping us to create resource groups without tags.
Can you please help us to resolve this issue.

Thanks,
Ajay

**Comment by kof-f** [comment]
Hey @ajayvarma560 we have now added support for customers to specify their own staging resource group. Please feel free to read about it here: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-json#properties-stagingresourcegroup
