### ISSUE TITLE
unable to build an image - Azure VM Image Builder Task 

### ISSUE THREAD

**Issue by azurenative** [danielsollondon/azvmimagebuilder#86]
Im just testing out the Azure VM Image Builder Task for azure devops.
unfortunately im getting this error .
1. the template name is undefined , cant find an input field for this.
_template name:  t_undefinedundefined_1606655517813_
2. the pipeline breaks after 7-8 minutes with below error.
##[error]Error: put template call failed for template t_undefinedundefined_1606655517813 with error: Internal error occurred. This is a generic error. To identify possible causes, go to https://aka.ms/azvmimagebuilderts. (CODE: 200)
Finishing: Azure VM Image Builder Task

anyone else could help me out ?

![builderror](https://user-images.githubusercontent.com/55314577/100543230-2f29b600-324f-11eb-9a7b-48558c30829d.PNG)

**Comment by danielsollondon** [comment]
Hi @azurenative - please can you raise a [support ticket](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#getting-support), we daily triage with the CSS support team for AIB.

You could also try checking the [template status](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#troubleshoot-image-template-submission-errors) that was submitted inside the devops task.
