### ISSUE TITLE
Azure Image builder failing with internal error

### ISSUE THREAD

**Issue by Mahisagar44** [danielsollondon/azvmimagebuilder#88]
<img width="452" alt="error" src="https://user-images.githubusercontent.com/45807138/101323287-738c0600-388e-11eb-8340-4d5faa1d1134.PNG">
<img width="741" alt="error1" src="https://user-images.githubusercontent.com/45807138/101323292-7555c980-388e-11eb-99db-01c247548fcb.PNG">

Hi Daniel,

I am facing this internal error issue from last week, intially the same script worked for me but now it was ending up with errors could you plese help me on this.

Thanks,
sagar

**Comment by danielsollondon** [comment]
Hi @Mahisagar44 - please can you raise a [support ticket](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-troubleshoot#getting-support), we daily triage with the CSS support team for AIB.

This looks like the submit is failing, can you check that the managed identity has permissions to all dependencies, including Azure Storage, and that you are not using the Azure Storage firewall.
