### ISSUE TITLE
Pass Multiple powershell files

### ISSUE THREAD

**Issue by bhupi-cloudeq** [danielsollondon/azvmimagebuilder#89]
Hi
Can we pass multiple powershell files or modules files in field "Inline customization script"

![image](https://user-images.githubusercontent.com/73111511/103076257-50ce5100-45f3-11eb-9407-1c32ef3f65c0.png)

Thanks

**Comment by danielsollondon** [comment]
@bhupi-cloudeq - apologies for the delay, you just use a new command on a new line, for example:

& 'c:\....\run1.ps1'
& 'c:\....\run2.ps1'

Docs are being updated!

**Comment by danielsollondon** [comment]
Doc PR has just gone in, should be there tomorrow.

**Comment by bhupi-cloudeq** [comment]
Hi @danielsollondon/azvmimagebuilder<mailto:reply@reply.github.com>

Thanks
Bhupinder Singh
