### ISSUE TITLE
Quota limit of standardDv2 family hit using Azure Image Builder

### ISSUE THREAD

**Issue by jackfruhecolab** [danielsollondon/azvmimagebuilder#9]
Hi, 

  It looks like some part of the packaging process tries to spin up a Dv2 family VM.
  
Right now I'm at my max quota for this - I know how to request an increase in quota.
  
**What I'd like to know is where in the process is the Dv2 being called and is there a configuration option to specify a different VM class.**

Thanks!

```
fddf68f1-6605-432d-9e8f-abf25c3f8059] PACKER ERR 2019/10/08 20:42:05 packer: 2019/10/08 20:42:05 Azure response status="400 Bad Request" method="POST"  
body="{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment 'pkrdpyew5c23775' is not valid according to the validation procedure. The tracking id is 'a5935223-a591-4e73-b9db-5a1aefc6e9d2'. See inner errors for details.\",
\"details\":[{\"code\":\"QuotaExceeded\",\"message\":\"The operation couldn't be completed as it results in exceeding quota limit of standardDv2Family Cores. Maximum allowed: 10, Current in use: 22, Additional requested: 1. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits.
```

- Jack

**Comment by danielsollondon** [comment]
Hi, we use Dv2 by default, however, we are about to let you to specify a VM SKU, this documentation will be released early next week. Stay tuned, I will come back to this thread.

**Comment by danielsollondon** [comment]
Just an update, we are still testing, I will update very soon.

**Comment by danielsollondon** [comment]
We now have support to update the VM size that Image Builder uses, see December update: https://github.com/danielsollondon/azvmimagebuilder#december-2019-updates
