### ISSUE TITLE
Error in executing script

### ISSUE THREAD

**Issue by bhupi-cloudeq** [danielsollondon/azvmimagebuilder#90]
Hi

![Capture](https://user-images.githubusercontent.com/73111511/103098758-f6081a00-4631-11eb-809f-032834c92ec7.PNG)

Facing below error, Earlier it was working.

[error.txt](https://github.com/danielsollondon/azvmimagebuilder/files/5740148/error.txt)

It would be helpful If you can look into it on priority.

Thanks

**Comment by danielsollondon** [comment]
apologies, I was behind, can you raise a support case for this please? 

Please ensure you select the right routing path and we will review in the daily triage: #65
