### ISSUE TITLE
Link to non-existent file

### ISSUE THREAD

**Issue by tsrob50** [danielsollondon/azvmimagebuilder#95]
Line 18 in1_Optimize_OS_for_WVD.ps1 located at azvmimagebuilder/solutions/14_Building_Images_WVD/1_Optimize_OS_for_WVD.ps1 has a link to non-existent file, causing an error when ran.

**Comment by danielsollondon** [comment]
Thanks, I'm working on a doc update, I will update this v soon.

**Comment by danielsollondon** [comment]
Thanks @tsrob50, I have fixed this now! Thank you for the YouTube videos you have posted!
