### ISSUE TITLE
For the New Subscription need to set Enable Microsoft.Network

### ISSUE THREAD

**Issue by iop45636** [danielsollondon/azvmimagebuilder#96]
We have the new subscription and test to create the AIB DevOps task. Then We found the missing information below:
1. New Subscription need to enable the provider of **Microsoft.Network**
2. About the $netRoleDefName on the az role assignment create command. The Azure CLI cannot find the variable.

**Comment by danielsollondon** [comment]
Thanks - I'm working on a large doc update,i will address this v soon.

**Comment by danielsollondon** [comment]
The AIB public docs have been updated and: https://github.com/Azure/azvmimagebuilder/tree/main/solutions/1_Azure_DevOps
