### ISSUE TITLE
Internal error occered trying to run build

### ISSUE THREAD

**Issue by BladeFireLight** [danielsollondon/azvmimagebuilder#97]
Our existing devops pipeline broke with no changes on our side. 

so I decided to try the new PowerShell commands so see if that would run. 

using https://docs.microsoft.com/en-us/azure/virtual-machines/windows/image-builder-powershell as a guide 

I get this problem

LastRunStatusMessage         : Internal error occurred. This is a generic error. To identify possible causes, go to
                               https://aka.ms/azvmimagebuilderts.
LastRunStatusRunState        : Failed

I also notice the IT_* RG that is crated has no logs

so as of right now I cant get AIB to work for any of my existing or new images.

**Comment by danielsollondon** [comment]
@BladeFireLight - this may be related to the incident we resolved earlier this week, is this working now?

**Comment by BladeFireLight** [comment]
yes it was related to the storage issue.
________________________________

**Comment by danielsollondon** [comment]
Thanks for letting me know.
