### ISSUE TITLE
Timeout running Remove-AzImageBuilderTemplate

### ISSUE THREAD

**Issue by BladeFireLight** [danielsollondon/azvmimagebuilder#98]
Remove-AzImageBuilderTemplate -ImageTemplateName $imageTemplateName -ResourceGroupName $imageResourceGroup

Remove-AzImageBuilderTemplate_Delete: The gateway did not receive a response from 'Microsoft.VirtualMachineImages' within the specified time period.

**Comment by danielsollondon** [comment]
Sorry for the delay, @BladeFireLight - are you still seeing this? If so, can you raise a case and we'll take a look, please ensure you select the right routing path and we will review in the daily triage: #65
