### ISSUE TITLE
Timeout when trying to build

### ISSUE THREAD

**Issue by PadreGregor** [danielsollondon/azvmimagebuilder#99]
Devops Pipeline without change run once then started giving the following errors  :

some of the run fails wit this:
Starting: Azure VM Image Builder Task

Task         : Azure VM Image Builder Test(Preview)
Description  : Build images using Azure Image Builder resource provider.
Version      : 1.0.20
Author       : Microsoft Corporation
Help         : For documentation, and end to end example, please visit: http://aka.ms/azvmimagebuilderdevops

start reading task parameters...
found build at:  D:\a\1\s\Packages
end reading parameters
getting storage account details for ********
created archive D:\a\_temp\temp_web_package_6985100633459513.zip
Source for image:  { type: 'PlatformImage',
  publisher: 'MicrosoftWindowsServer',
  offer: 'WindowsServer',
  sku: '2016-Datacenter',
  version: '14393.4169.2101090332' }
template name:  t_undefinedundefined_1612366538082
starting put template...
put template:  Succeeded
starting run template...
##[error]Error: post template call failed for template t_undefinedundefined_1612366538082 with error: The gateway did not receive a response from 'Microsoft.VirtualMachineImages' within the specified time period. (CODE: 504)

some fails wit a generic:
ut template:  Succeeded
starting run template...
##[error]Error: post template call failed for template t_undefinedundefined_1612437693756 with error: Internal error occurred. This is a generic error. To identify possible causes, go to https://aka.ms/azvmimagebuilderts. (CODE: 200)
Finishing: Azure VM Image Builder Task

and no log file created in the IT_.... storage account

**Comment by danielsollondon** [comment]
@PadreGregor - are you still seeing this issue? We had an incident in some of the US regions that may have caused this.

**Comment by PadreGregor** [comment]
hi @danielsollondon 
was running a build it seems ok. now the c:\buildartifacts\Packages.zip seems corrupted. 
Regards

**Comment by danielsollondon** [comment]
Thanks @PadreGregor for letting me know.
